export type DiffParseError = "DIFF_EMPTY";

export type AstParseError =
  | "AST_INIT_FAILED"
  | "AST_LANGUAGE_NOT_SUPPORTED"
  | "AST_PARSE_FAILED";

export type ContextBuildError = "CONTEXT_NO_REVIEWABLE_FILES";

export type GitHubError =
  | "GITHUB_AUTH_FAILED"
  | "GITHUB_RATE_LIMITED"
  | "GITHUB_NOT_FOUND"
  | "GITHUB_FORBIDDEN"
  | "GITHUB_UNKNOWN_ERROR";

export type ReviewEngineError =
  | "REVIEW_ALREADY_EXISTS"
  | "REVIEW_DIFF_FETCH_FAILED"
  | "REVIEW_DIFF_PARSE_FAILED"
  | "REVIEW_LLM_FAILED"
  | "REVIEW_POST_FAILED"
  | "REVIEW_UNEXPECTED_ERROR"
  | "REVIEW_DB_ERROR";

export type QueueError = "QUEUE_ENQUEUE_FAILED";

export type WebhookHandlerError =
  | "INVALID_PAYLOAD"
  | "INSTALLATION_SAVE_FAILED"
  | "INSTALLATION_DELETE_FAILED"
  | "REVIEW_ENQUEUE_FAILED";
